import {
  createTheme,
  CSSVariablesResolver,
  DEFAULT_THEME,
  MantineTheme,
} from "@mantine/core";

const AVANDAR_BLUE_SHADES = [
  "#edf6ff",
  "#d8ebff",
  "#b9dcff",
  "#89c7ff",
  "#51a7ff",
  "#2983ff",
  "#1563fe", // official brand color
  "#0b4aea",
  "#103dbd",
  "#143894",
] as const;

const NEUTRAL_SHADES = [
  "#f0f4f8",
  "#d9e2ec",
  "#bcccdc",
  "#9fb3c8",
  "#829ab1",
  "#627d98",
  "#486581",
  "#334e68",
  "#243b53",
  "#102a43",
] as const;

export const Theme = createTheme({
  scale: 1, // root font size is 1rem = 16px
  fontFamily: "Figtree, sans-serif",
  primaryShade: { light: 6, dark: 8 },

  /**
   * This is the color that Mantine will use as the default for UI elements
   * like buttons, links, or headlines.
   */
  primaryColor: "primary",
  colors: {
    /**
     * Our primary brand color.
     * Scale generated by uicolors.app with #1563fe as the base
     */
    primary: AVANDAR_BLUE_SHADES,

    /**
     * Supporting or accent color. Use sparingly to accent UI elements
     * like buttons, links, or headlines.
     *
     * Scale from Refactoring UI Palette 2 - Yellow (Vivid)
     */
    secondary: [
      "#fffbea",
      "#fff3c4",
      "#fce588",
      "#fadb5f",
      "#f7c948",
      "#f0b429",
      "#de911d",
      "#cb6e17",
      "#b44d12",
      "#8d2b0b",
    ] as const,

    /** Positive states, E.g. completed, passed, saved */
    success: [
      "#eafcef",
      "#d9f6df",
      "#b1ebbe",
      "#86e09a",
      "#63d77c",
      "#4dd269",
      "#40cf5e",
      "#31b74e",
      "#27a343",
      "#168d36",
    ] as const,

    /** Warning states, E.g. approaching limits, risky actions */
    warning: [
      "#fffae2",
      "#fdf4ce",
      "#fae8a0",
      "#f6db6d",
      "#f4d043",
      "#f2c928",
      "#f1c617",
      "#d7ae06",
      "#bf9b00",
      "#a58500",
    ] as const,

    /** Negative states, E.g. errors, failed, deleted, invalid */
    danger: [
      "#ffebe8",
      "#ffd6d2",
      "#f6ada5",
      "#ef8075",
      "#e95a4c",
      "#e64231",
      "#e53523",
      "#cb2717",
      "#b61f13",
      "#a0140c",
    ] as const,

    /** Informational content (tooltips, messages) */
    info: [
      "#e6fcff",
      "#d5f5fa",
      "#abe9f3",
      "#7edcec",
      "#5dd2e6",
      "#49cce2",
      "#3bc9e1",
      "#2bb1c8",
      "#169eb3",
      "#00899d",
    ] as const,

    /**
     * Neutral colors for backgrounds. E.g. cards, panels.
     * (Scale from Refactoring UI Palette 2 - Blue Grey)
     */
    neutral: NEUTRAL_SHADES,
  },

  breakpoints: {
    xs: "36em", // 576px - small phones (e.g. iPhone SE)
    sm: "48em", // 768px - tablets/large phones
    md: "62em", // 992px - small laptops/tablets landscape
    lg: "75em", // 1200px - standard laptops/desktops
    xl: "88em", // 1408px - large desktops/4K displays
  },

  spacing: {
    xxxs: "calc(0.125rem * var(--mantine-scale))", // 2px
    xxs: "calc(0.25rem * var(--mantine-scale))", // 4px
    xs: "calc(0.5rem * var(--mantine-scale))", // 8px
    sm: "calc(0.75rem * var(--mantine-scale))", // 12px
    md: "calc(1rem * var(--mantine-scale))", // 16px
    lg: "calc(1.5rem * var(--mantine-scale))", // 24px
    xl: "calc(2rem * var(--mantine-scale))", // 32px
    xxl: "calc(3rem * var(--mantine-scale))", // 48px
    xxxl: "calc(4rem * var(--mantine-scale))", // 64px
  },

  other: {
    navbar: {
      backgroundColor: NEUTRAL_SHADES[6],
      textColor: DEFAULT_THEME.white,
      hoverBackgroundColor: NEUTRAL_SHADES[7],
      activeBackgroundColor: NEUTRAL_SHADES[7],
      activeHoverBackgroundColor: NEUTRAL_SHADES[7],
    },
  },
});

export const cssVariablesResolver: CSSVariablesResolver = (
  theme: MantineTheme,
) => {
  return {
    variables: {
      // new custom colors
      "--mantine-navbar-background": theme.other.navbar.backgroundColor,
      "--mantine-navbar-color": theme.other.navbar.textColor,
      "--mantine-navbar-hover-background":
        theme.other.navbar.hoverBackgroundColor,
      "--mantine-navbar-active-background":
        theme.other.navbar.activeBackgroundColor,
      "--mantine-navbar-active-hover-background":
        theme.other.navbar.activeHoverBackgroundColor,
    },
    dark: {
      "--mantine-color-body": theme.colors.neutral[0],
      "--mantine-color-text": theme.colors.neutral[9],
    },
    light: {
      "--mantine-color-body": theme.colors.neutral[0],
      "--mantine-color-text": theme.colors.neutral[9],
    },
  };
};
